language: node_js

node_js:
  - 0.10

notifications:
  email:
    recipients:
      - magic@wizardtales.com

before_script:
    - sudo apt-get install python-software-properties
    - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
    - sudo add-apt-repository 'deb http://ftp.osuosl.org/pub/mariadb/repo/10.0/ubuntu precise main'
    - sudo apt-get update
    - sudo apt-get purge mysql*
    - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install mariadb-server-10.0 -y
    - mysql -e "create database db_migrate_test;"
    - createdb db_migrate_test
    - cp test/db.config.ci test/db.config.json