language: node_js

node_js:
  - 0.10
  - 0.12
  - io.js

notifications:
  email:
    recipients:
      - magic@wizardtales.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/509c88551a18006fe93f
    on_success: change
    on_failure: always
    on_start: false

services:
  - mongodb

sudo: false

cache: npm

addons:
  apt:
    sources:
      - mariadb-10.0
    packages:
      - mariadb-server

env:
    - DB=mysql
    - DB=mariadb
    - DB=postgres92
    - DB=postgres93

before_script:
    - until nc -z localhost 27017 ; do echo Waiting for MongoDB; sleep 1; done
    - sh -c "if [ '$DB' = 'postgres92' ]; then sudo /etc/init.d/postgresql stop && sudo /etc/init.d/postgresql start 9.2; fi"
    - sh -c "if [ '$DB' = 'postgres93' ]; then sudo /etc/init.d/postgresql stop && sudo /etc/init.d/postgresql start 9.3; fi"
    - mysql -e "create database db_migrate_test;"
    - createdb db_migrate_test
    - cp test/db.config.ci test/db.config.json
