
services:
  - mongodb
  - postgresql
  - mysql
  
environment:
  MYSQL_PWD: Password12!
  matrix:
    - node: "5"

install:
  - ps: Install-Product node $env:node
  - IF %node% LSS 1 npm -g install npm
  - IF %node% LSS 1 set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - cp test/db.config.waci test/db.config.json
  
test_script:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET PATH=C:\Program Files\PostgreSQL\9.3\bin\;%PATH%          
  - createdb db_migrate_test
  - '"C:\Program Files\MySql\MySQL Server 5.6\bin\mysql" -e "create database db_migrate_test;" --user=root --password=Password12!'
  - node --version
  - npm --version
  - ./node_modules/.bin/vows.cmd
  
build: off
